{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "911305e6-cfea-4a04-ba3b-3ed4e4df6255",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\core\\exceptions.py:55: UserWarning: cannot initiate Sentry error reporting: unknown error.\n",
      "  UserWarning)\n",
      "[INFO]: No release version set. Setting default to DR17\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\1431842484.py\", line 1, in <module>\n",
      "    from marvin.tools.query import Query\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 772, in <module>\n",
      "    config = MarvinConfig()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 123, in __init__\n",
      "    self._check_config()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 461, in _check_config\n",
      "    log.info('No release version set. Setting default to {0}'.format(latest))\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1370, in info\n",
      "    Log 'msg % args' with severity 'INFO'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1378, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: 'No release version set. Setting default to DR17'\n",
      "Arguments: ()\n",
      "[WARNING]: path C:\\Users\\oryan\\sas\\dr17/manga/spectro/redux\\v3_1_1\\drpall-v3_1_1.fits cannot be found. Setting drpall to None. (MarvinUserWarning)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\1431842484.py\", line 1, in <module>\n",
      "    from marvin.tools.query import Query\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 772, in <module>\n",
      "    config = MarvinConfig()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 129, in __init__\n",
      "    self.setDefaultDrpAll()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 226, in setDefaultDrpAll\n",
      "    self.drpall = self._getDrpAllPath(drpver)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 387, in drpall\n",
      "    .format(value), MarvinUserWarning)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\warnings.py\", line 110, in _showwarnmsg\n",
      "    msg.file, msg.line)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 2096, in _showwarning\n",
      "    logger.warning(\"%s\", s)\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1382, in warning\n",
      "    Log 'msg % args' with severity 'WARNING'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1390, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: '%s'\n",
      "Arguments: ('C:\\\\Users\\\\oryan\\\\AppData\\\\Local\\\\Continuum\\\\anaconda3\\\\lib\\\\site-packages\\\\marvin\\\\__init__.py:387: MarvinUserWarning: path C:\\\\Users\\\\oryan\\\\sas\\\\dr17/manga/spectro/redux\\\\v3_1_1\\\\drpall-v3_1_1.fits cannot be found. Setting drpall to None.\\n  .format(value), MarvinUserWarning)\\n',)\n",
      "[WARNING]: path C:\\Users\\oryan\\sas\\dr17/manga/spectro/analysis\\v3_1_1\\3.1.0\\dapall-v3_1_1-3.1.0.fits cannot be found. Setting dapall to None. (MarvinUserWarning)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\1431842484.py\", line 1, in <module>\n",
      "    from marvin.tools.query import Query\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 772, in <module>\n",
      "    config = MarvinConfig()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 129, in __init__\n",
      "    self.setDefaultDrpAll()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 227, in setDefaultDrpAll\n",
      "    self.dapall = self._getDapAllPath(drpver, dapver)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 400, in dapall\n",
      "    .format(value), MarvinUserWarning)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\warnings.py\", line 110, in _showwarnmsg\n",
      "    msg.file, msg.line)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 2096, in _showwarning\n",
      "    logger.warning(\"%s\", s)\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1382, in warning\n",
      "    Log 'msg % args' with severity 'WARNING'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1390, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: '%s'\n",
      "Arguments: ('C:\\\\Users\\\\oryan\\\\AppData\\\\Local\\\\Continuum\\\\anaconda3\\\\lib\\\\site-packages\\\\marvin\\\\__init__.py:400: MarvinUserWarning: path C:\\\\Users\\\\oryan\\\\sas\\\\dr17/manga/spectro/analysis\\\\v3_1_1\\\\3.1.0\\\\dapall-v3_1_1-3.1.0.fits cannot be found. Setting dapall to None.\\n  .format(value), MarvinUserWarning)\\n',)\n",
      "[WARNING]: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'view_args'} (RemovedInMarshmallow4Warning)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\1431842484.py\", line 1, in <module>\n",
      "    from marvin.tools.query import Query\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 788, in <module>\n",
      "    from marvin.api.api import Interaction\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\api\\__init__.py\", line 27, in <module>\n",
      "    validate.Regexp('^[0-9-]*$')]),\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marshmallow\\fields.py\", line 227, in __init__\n",
      "    stacklevel=2,\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\warnings.py\", line 110, in _showwarnmsg\n",
      "    msg.file, msg.line)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 2096, in _showwarning\n",
      "    logger.warning(\"%s\", s)\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1382, in warning\n",
      "    Log 'msg % args' with severity 'WARNING'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1390, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: '%s'\n",
      "Arguments: (\"C:\\\\Users\\\\oryan\\\\AppData\\\\Local\\\\Continuum\\\\anaconda3\\\\lib\\\\site-packages\\\\marvin\\\\api\\\\__init__.py:27: RemovedInMarshmallow4Warning: Passing field metadata as keyword arguments is deprecated. Use the explicit `metadata=...` argument instead. Additional metadata: {'location': 'view_args'}\\n  validate.Regexp('^[0-9-]*$')]),\\n\",)\n",
      "[WARNING]: The 'missing' argument to fields is deprecated. Use 'load_default' instead. (RemovedInMarshmallow4Warning)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\1431842484.py\", line 1, in <module>\n",
      "    from marvin.tools.query import Query\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 788, in <module>\n",
      "    from marvin.api.api import Interaction\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\api\\__init__.py\", line 69, in <module>\n",
      "    'order': fields.String(missing='asc', validate=validate.OneOf(['asc', 'desc'])),\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marshmallow\\fields.py\", line 188, in __init__\n",
      "    stacklevel=2,\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\warnings.py\", line 110, in _showwarnmsg\n",
      "    msg.file, msg.line)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 2096, in _showwarning\n",
      "    logger.warning(\"%s\", s)\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1382, in warning\n",
      "    Log 'msg % args' with severity 'WARNING'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1390, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: '%s'\n",
      "Arguments: (\"C:\\\\Users\\\\oryan\\\\AppData\\\\Local\\\\Continuum\\\\anaconda3\\\\lib\\\\site-packages\\\\marvin\\\\api\\\\__init__.py:69: RemovedInMarshmallow4Warning: The 'missing' argument to fields is deprecated. Use 'load_default' instead.\\n  'order': fields.String(missing='asc', validate=validate.OneOf(['asc', 'desc'])),\\n\",)\n",
      "[WARNING]: distutils Version classes are deprecated. Use packaging.version instead. (DeprecationWarning)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\1431842484.py\", line 1, in <module>\n",
      "    from marvin.tools.query import Query\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\__init__.py\", line 792, in <module>\n",
      "    from . import tools\n",
      "  File \"<frozen importlib._bootstrap>\", line 1035, in _handle_fromlist\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\__init__.py\", line 3, in <module>\n",
      "    from . import cube, maps, modelcube, spaxel\n",
      "  File \"<frozen importlib._bootstrap>\", line 1035, in _handle_fromlist\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\cube.py\", line 23, in <module>\n",
      "    import marvin.tools.maps\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\maps.py\", line 30, in <module>\n",
      "    import marvin.tools.modelcube\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\modelcube.py\", line 29, in <module>\n",
      "    from marvin.tools.quantities import DataCube, Map, Spectrum\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\quantities\\__init__.py\", line 6, in <module>\n",
      "    from .map import EnhancedMap, Map\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\quantities\\map.py\", line 31, in <module>\n",
      "    from marvin.tools.mixins.caching import CacheMixIn\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\mixins\\__init__.py\", line 4, in <module>\n",
      "    from .dapall import *\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\mixins\\dapall.py\", line 25, in <module>\n",
      "    class DAPallMixIn(object):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\mixins\\dapall.py\", line 38, in DAPallMixIn\n",
      "    __min_dapall_version__ = distutils.version.StrictVersion('2.1.0')\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\setuptools\\_distutils\\version.py\", line 59, in __init__\n",
      "    stacklevel=2,\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\warnings.py\", line 110, in _showwarnmsg\n",
      "    msg.file, msg.line)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 2096, in _showwarning\n",
      "    logger.warning(\"%s\", s)\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1382, in warning\n",
      "    Log 'msg % args' with severity 'WARNING'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1390, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: '%s'\n",
      "Arguments: (\"C:\\\\Users\\\\oryan\\\\AppData\\\\Local\\\\Continuum\\\\anaconda3\\\\lib\\\\site-packages\\\\marvin\\\\tools\\\\mixins\\\\dapall.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.\\n  __min_dapall_version__ = distutils.version.StrictVersion('2.1.0')\\n\",)\n"
     ]
    }
   ],
   "source": [
    "from marvin.tools.query import Query\n",
    "import pandas as pd\n",
    "\n",
    "from IPython.display import clear_output\n",
    "\n",
    "from tqdm import tqdm\n",
    "\n",
    "import sys"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "63bfbe7a-b203-47b5-8166-31227b8628c8",
   "metadata": {},
   "source": [
    "### Getting Coordinates"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "316a03dd-bd21-44bf-85a2-3f0f8e818f24",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('C:/Users/oryan/Documents/PySPAM_Original_Python_MCMC/APySPAM_MCMC/data/all_coords.csv', index_col = 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bf912d12-961e-4092-8742-85a9d1b6c5f7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Prim_RA', 'Prim_DEC', 'Names', 'Sec_RA', 'Sec_DEC'], dtype='object')"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "29799bff-2530-491b-a7db-471d93fdce96",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_prims = (\n",
    "    df[['Names', 'Prim_RA', 'Prim_DEC']]\n",
    "    .assign(names_diff = df.Names.apply(lambda x: x + '_1'))\n",
    "    .rename(columns = {'Prim_RA':'RA', 'Prim_DEC': 'Dec'})\n",
    ")\n",
    "df_secs = (\n",
    "    df[['Names', 'Sec_RA', 'Sec_DEC']]\n",
    "    .assign(names_diff = df.Names.apply(lambda x: x + '_2'))\n",
    "    .rename(columns = {'Sec_RA' : 'RA', 'Sec_DEC' : 'Dec'})\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "27c41e88-2a46-4f95-a3d0-28a54cc48ac2",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_comb = pd.concat([df_prims, df_secs]).drop(columns = 'Names')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "33d5f05a-d752-4cad-9870-65c7e1e3dfce",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>RA</th>\n",
       "      <th>Dec</th>\n",
       "      <th>names_diff</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>204.970333</td>\n",
       "      <td>0.839844</td>\n",
       "      <td>Arp240_1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>30.957167</td>\n",
       "      <td>14.738644</td>\n",
       "      <td>Arp290_1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>144.433333</td>\n",
       "      <td>2.760164</td>\n",
       "      <td>Arp142_1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>32.352333</td>\n",
       "      <td>-10.136006</td>\n",
       "      <td>Arp318_1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4.708583</td>\n",
       "      <td>-10.361625</td>\n",
       "      <td>Arp256_1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>1.683208</td>\n",
       "      <td>-6.635019</td>\n",
       "      <td>Arp146_2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>116.726000</td>\n",
       "      <td>39.015025</td>\n",
       "      <td>Arp143_2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>20.863542</td>\n",
       "      <td>30.771967</td>\n",
       "      <td>Arp70_2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>238.392917</td>\n",
       "      <td>18.603722</td>\n",
       "      <td>Arp218_2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>53</th>\n",
       "      <td>1.067292</td>\n",
       "      <td>3.376900</td>\n",
       "      <td>Violin_Clef_2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>108 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            RA        Dec     names_diff\n",
       "0   204.970333   0.839844       Arp240_1\n",
       "1    30.957167  14.738644       Arp290_1\n",
       "2   144.433333   2.760164       Arp142_1\n",
       "3    32.352333 -10.136006       Arp318_1\n",
       "4     4.708583 -10.361625       Arp256_1\n",
       "..         ...        ...            ...\n",
       "49    1.683208  -6.635019       Arp146_2\n",
       "50  116.726000  39.015025       Arp143_2\n",
       "51   20.863542  30.771967        Arp70_2\n",
       "52  238.392917  18.603722       Arp218_2\n",
       "53    1.067292   3.376900  Violin_Clef_2\n",
       "\n",
       "[108 rows x 3 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_comb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "05f840c3-09b3-4487-93dd-1de7bb55c696",
   "metadata": {},
   "outputs": [],
   "source": [
    "myfilter = f'radial({df_comb.RA.iloc[0]}, {df_comb.Dec.iloc[0]}, 0.5)'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f450f39a-7c2b-4d2e-af49-95630341bc02",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[WARNING]: No local database found. Cannot perform queries. (MarvinUserWarning)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\2500783807.py\", line 1, in <module>\n",
      "    q = Query(search_filter = myfilter)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 196, in __init__\n",
      "    self._set_mma()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 229, in _set_mma\n",
      "    self._do_local()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 241, in _do_local\n",
      "    warnings.warn('No local database found. Cannot perform queries.', MarvinUserWarning)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\warnings.py\", line 110, in _showwarnmsg\n",
      "    msg.file, msg.line)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 2096, in _showwarning\n",
      "    logger.warning(\"%s\", s)\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1382, in warning\n",
      "    Log 'msg % args' with severity 'WARNING'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1390, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: '%s'\n",
      "Arguments: (\"C:\\\\Users\\\\oryan\\\\AppData\\\\Local\\\\Continuum\\\\anaconda3\\\\lib\\\\site-packages\\\\marvin\\\\tools\\\\query.py:241: MarvinUserWarning: No local database found. Cannot perform queries.\\n  warnings.warn('No local database found. Cannot perform queries.', MarvinUserWarning)\\n\",)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 229, in _set_mma\n",
      "    self._do_local()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 242, in _do_local\n",
      "    raise MarvinError('No local database found.  Query cannot be run in local mode')\n",
      "marvin.core.exceptions.MarvinError: No local database found.  Query cannot be run in local mode.\n",
      "You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).\n",
      "Fill out a subject and some text describing the error that just occurred.\n",
      "If able, copy and paste the full traceback information into the issue as well.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\2500783807.py\", line 1, in <module>\n",
      "    q = Query(search_filter = myfilter)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 196, in __init__\n",
      "    self._set_mma()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 231, in _set_mma\n",
      "    log.debug('local mode failed. Trying remote now.')\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1358, in debug\n",
      "    Log 'msg % args' with severity 'DEBUG'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1366, in debug\n",
      "    self._log(DEBUG, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: 'local mode failed. Trying remote now.'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "q = Query(search_filter = myfilter)\n",
    "r = q.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "40fc1e65-ddb4-40ef-86e4-a8d69907d441",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "68\n"
     ]
    }
   ],
   "source": [
    "print(i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "c50952c7-5210-4af5-871f-b8b597041a2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 62%|██████▏   | 67/108 [00:33<00:20,  1.97it/s]--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 229, in _set_mma\n",
      "    self._do_local()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 242, in _do_local\n",
      "    raise MarvinError('No local database found.  Query cannot be run in local mode')\n",
      "marvin.core.exceptions.MarvinError: No local database found.  Query cannot be run in local mode.\n",
      "You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).\n",
      "Fill out a subject and some text describing the error that just occurred.\n",
      "If able, copy and paste the full traceback information into the issue as well.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\870714877.py\", line 8, in <module>\n",
      "    q = Query(search_filter = myfilter)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 196, in __init__\n",
      "    self._set_mma()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 231, in _set_mma\n",
      "    log.debug('local mode failed. Trying remote now.')\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1358, in debug\n",
      "    Log 'msg % args' with severity 'DEBUG'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1366, in debug\n",
      "    self._log(DEBUG, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: 'local mode failed. Trying remote now.'\n",
      "Arguments: ()\n",
      " 63%|██████▎   | 68/108 [00:34<00:28,  1.40it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found Data!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 229, in _set_mma\n",
      "    self._do_local()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 242, in _do_local\n",
      "    raise MarvinError('No local database found.  Query cannot be run in local mode')\n",
      "marvin.core.exceptions.MarvinError: No local database found.  Query cannot be run in local mode.\n",
      "You can submit this error to Marvin GitHub Issues (https://github.com/sdss/marvin/issues/new).\n",
      "Fill out a subject and some text describing the error that just occurred.\n",
      "If able, copy and paste the full traceback information into the issue as well.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 70, in emit\n",
      "    self.doRollover()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 394, in doRollover\n",
      "    self.rotate(self.baseFilename, dfn)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\handlers.py\", line 111, in rotate\n",
      "    os.rename(source, dest)\n",
      "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log' -> 'C:\\\\Users\\\\oryan\\\\.marvin\\\\marvin.log.2022-09-27_00:00:00'\n",
      "Call stack:\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2915, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3186, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Temp\\ipykernel_17912\\870714877.py\", line 8, in <module>\n",
      "    q = Query(search_filter = myfilter)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 196, in __init__\n",
      "    self._set_mma()\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\marvin\\tools\\query.py\", line 231, in _set_mma\n",
      "    log.debug('local mode failed. Trying remote now.')\n",
      "  File \"c:\\users\\oryan\\appdata\\local\\continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1358, in debug\n",
      "    Log 'msg % args' with severity 'DEBUG'.\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1366, in debug\n",
      "    self._log(DEBUG, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\oryan\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\sdsstools\\logger.py\", line 306, in handle\n",
      "    return super().handle(record)\n",
      "Message: 'local mode failed. Trying remote now.'\n",
      "Arguments: ()\n",
      " 63%|██████▎   | 68/108 [00:35<00:20,  1.91it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found Data!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "for i in tqdm(range(len(df_comb))):\n",
    "    row = df_comb.iloc[i]\n",
    "    ra = row.RA\n",
    "    dec = row.Dec\n",
    "    \n",
    "    myfilter = f'radial({ra}, {dec}, 0.01)'\n",
    "    \n",
    "    q = Query(search_filter = myfilter)\n",
    "    r = q.run()\n",
    "    \n",
    "    if len(r.results) > 0:\n",
    "        print('Found Data!')\n",
    "        \n",
    "        if i == 7 or i == 14 or i == 59 or i == 61 or i == 67: # or i == 68:\n",
    "            continue\n",
    "        \n",
    "        sys.exit()\n",
    "    else:\n",
    "        clear_output(wait = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "703cd9db-fb49-4852-b6aa-c95ebe11d861",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "RA            205.419167\n",
       "Dec             55.67385\n",
       "names_diff      Arp239_2\n",
       "Name: 14, dtype: object"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_comb.iloc[i]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "f0838113-63b2-4c77-abef-1bfd0ff311e8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<ResultSet(set=1.0/1, index=0:2, count_in_set=2, total=2)>\n",
       "[ResultRow(mangaid='1-591997', plateifu='11020-6103', ra=205.432335253, dec=55.6737595258),\n",
       " ResultRow(mangaid='1-627026', plateifu='11013-3702', ra=205.415065461, dec=55.6706474881)]"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[WARNING]: unclosed socket <zmq.Socket(zmq.PUSH) at 0x227bda4ec88> (ResourceWarning)\n"
     ]
    }
   ],
   "source": [
    "r.results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "833f456e-e480-4436-9575-c828b064e329",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
